### ISSUE TITLE
Patch Size and Number in Ablation

### ISSUE THREAD

**Issue by JLiu-Edinburgh** [tsb0601/EMP-SSL#2]
Hi,

Congratulations for such a wonderful work in SSL domain.

My question is concerned with the experiment configurations. It seems that fixed patch sizes were used in comparison and ablation experiments, which can allow the model to "see" image information extremely more times, compared to image-based augmentation methods. It is reasonable to **reduce the patch size** with **an increase in patch number**, i.e. maintain the pixel count for a single forward pass with augmented images or patches as input.

Thanks for your nice ideas.

**Comment by tsb0601** [comment]
Hi,

Thank you for the interest in our work and your kind words!!! 

Yes, in this study, we employed fixed-size image patches throughout the training process. We adhered to the bag-of-features evaluation method proposed in the I2-VICReg study (https://arxiv.org/abs/2206.08954). From a metric standpoint, this alternative evaluation approach could yield an increase of up to 2% for the proposed method, as highlighted in the I2-VICReg paper.

The primary focus of our work is to confirm that learning the statistical occurrence in patches is a critical factor for success in joint-embedding self-supervised learning and increasing number of patches would promote this learning process. We consider it to be less important during our study.

We also believe the extreme patch raised in this work are transferable towards image-based augmentation methods.

Thank you for suggestion!
