### ISSUE TITLE
The Loss contractive, Loss TCR, Loss Total are all lower than zero. Is it a normal situation ?

### ISSUE THREAD

**Issue by ray-lee-94** [tsb0601/EMP-SSL#6]
![image](https://github.com/tsb0601/EMP-SSL/assets/30370620/90a7b6c3-f015-406c-8cf7-25843b392ead)

**Comment by tsb0601** [comment]
Hi,

It is quite normal. As we try to optimize the absolute value of loss to be larger, we set the loss value to be negative. One can reverse the sign to read the values.

Sincerely

**Comment by ray-lee-94** [comment]
![image](https://github.com/tsb0601/EMP-SSL/assets/30370620/6fcb3848-c718-4712-8f73-8177e580d192)

The learning rate and loss curve look strange
